"""
The deterministic digest that grounds the quality analyzer.

These are the facts the model is not allowed to guess at, so they have to be
right: what fraction of bullets carry a metric, which ones open with a duty
phrase, whether the dates are written one way or three.
"""

from backend.services.resume_extraction import build_profile
from backend.services.resume_metrics import build_digest, render_digest


RAW_TEXT = """Wissam Elmasry
elmasry.wissam@gmail.com | Gatineau, QC

PROFESSIONAL SUMMARY
Software engineer.

WORK EXPERIENCE
Public Services and Procurement Canada
- Responsible for maintaining the regression suite
- Cut deploy time by 40% across three services
- Reports were generated by the pipeline nightly

PROJECTS
Tailrd
- Shipped a Chrome extension

CERTIFICATIONS
AWS Solutions Architect
"""

PROFILE_DATA = {
    "name": "Wissam Elmasry",
    "email": "elmasry.wissam@gmail.com",
    "location": "Gatineau, QC",
    "summary": "Software engineer.",
    "experience": [{
        "company": "PSPC", "title": "Dev",
        "start_date": "Oct 2025", "end_date": "May 2026",
        "bullets": [
            "Responsible for maintaining the regression suite",
            "Cut deploy time by 40% across three services",
            "Reports were generated by the pipeline nightly",
        ],
    }],
    "projects": [{"name": "Tailrd", "start_date": "2025", "end_date": "2026",
                  "bullets": ["Shipped a Chrome extension"]}],
    "custom_sections": [{"title": "Certifications", "kind": "certifications",
                         "items": [{"title": "AWS Solutions Architect"}]}],
}


def digest():
    return build_digest(RAW_TEXT, build_profile(PROFILE_DATA))


def test_counts_every_bullet_across_every_section():
    d = digest()
    assert d["counts"]["bullets"] == 4
    assert d["counts"]["experience_entries"] == 1
    assert d["counts"]["project_entries"] == 1
    assert d["counts"]["custom_sections"] == 1


def test_quantification_and_strong_verb_coverage():
    d = digest()
    # One of four bullets carries a number ("40%").
    assert d["bullets"]["quantified_pct"] == 25
    # "Cut" and "Shipped" open strongly; "Responsible" and "Reports" do not.
    assert d["bullets"]["strong_verb_pct"] == 50
    assert len(d["bullets"]["unquantified"]) == 3


def test_finds_the_duty_phrase_and_the_passive_bullet_verbatim():
    d = digest()
    weak = d["language"]["weak_openers"]
    passive = d["language"]["passive_voice"]

    assert any("Responsible for maintaining" in w for w in weak)
    assert any("Reports were generated" in p for p in passive)
    # The strong, quantified bullet is not flagged as either.
    assert not any("Cut deploy time" in x for x in weak + passive)


def test_detects_sections_in_document_order():
    d = digest()
    assert d["sections_in_order"] == ["Summary", "Experience", "Projects", "Certifications"]
    assert d["has_summary"] is True


def test_date_format_consistency():
    consistent = digest()
    assert consistent["formatting"]["date_formats_used"] == ["Mon YYYY", "YYYY"]
    assert consistent["formatting"]["date_format_consistent"] is False

    single = build_digest("", build_profile({
        "experience": [{"company": "A", "start_date": "Jan 2024", "end_date": "Mar 2025"}],
    }))
    assert single["formatting"]["date_format_consistent"] is True


def test_reports_missing_contact_fields():
    d = digest()
    assert set(d["formatting"]["missing_contact"]) == {"phone", "linkedin"}


def test_filler_phrases_are_found_in_the_raw_text():
    d = build_digest("I am a results-driven team player.", build_profile({}))
    assert "team player" in d["language"]["filler_phrases"]
    assert "results-driven" in d["language"]["filler_phrases"]


def test_render_digest_states_the_facts_the_prompt_relies_on():
    text = render_digest(digest())
    assert "Bullets containing a number/metric: 25%" in text
    assert "Responsible for maintaining the regression suite" in text
    assert "INCONSISTENT" in text
