import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { BRAND_COLORS, FAVICON, MARK, WORDMARK } from "../components/brand";

// The standalone files are generated by scripts/brand/build-brand.mjs; these
// checks catch a stale regeneration and enforce the file rules in brand/README.md.
const ROOT = path.resolve(__dirname, "..", "..");
const ASSETS = path.join(ROOT, "src", "assets", "brand");
const read = (p: string) => readFileSync(p, "utf8");
const svgs = readdirSync(ASSETS).filter((f) => f.endsWith(".svg"));

describe("standalone brand SVGs", () => {
  it("ships the full set", () => {
    expect(svgs.sort()).toEqual(
      [
        "tailrd-app-icon.svg",
        "tailrd-logo-horizontal-dark.svg",
        "tailrd-logo-horizontal-mono-black.svg",
        "tailrd-logo-horizontal-mono-white.svg",
        "tailrd-logo-horizontal.svg",
        "tailrd-logo-stacked-dark.svg",
        "tailrd-logo-stacked.svg",
        "tailrd-mark-dark.svg",
        "tailrd-mark-mono-black.svg",
        "tailrd-mark-mono-white.svg",
        "tailrd-mark.svg",
        "tailrd-wordmark-dark.svg",
        "tailrd-wordmark.svg",
      ].sort(),
    );
  });

  it.each(svgs)("%s follows the file rules", (name) => {
    const svg = read(path.join(ASSETS, name));
    const root = svg.slice(0, svg.indexOf(">") + 1);
    expect(root).toContain('role="img"');
    expect(root).toContain('viewBox="');
    expect(root).not.toMatch(/\s(width|height)=/);
    expect(svg).toContain("<title>Tailrd</title>");
    expect(svg).not.toMatch(/<style|\sclass=|\sid=|<text/);
    expect(svg.split("\n").length).toBeGreaterThan(5); // formatted, not minified
  });

  it.each(svgs.filter((n) => !n.includes("wordmark") && !n.includes("app-icon")))(
    "%s carries the pinned mark geometry",
    (name) => {
      const svg = read(path.join(ASSETS, name));
      for (const d of [MARK.ring, MARK.plane, ...MARK.folds, ...MARK.trail]) expect(svg).toContain(`d="${d}"`);
    },
  );

  it.each(svgs.filter((n) => n.includes("horizontal") || n.includes("stacked") || n.includes("wordmark")))(
    "%s carries the pinned lettering",
    (name) => {
      const svg = read(path.join(ASSETS, name));
      for (const d of Object.values(WORDMARK.glyphs)) expect(svg).toContain(`d="${d}"`);
    },
  );

  it("colours the light lockup with the exact primary", () => {
    const svg = read(path.join(ASSETS, "tailrd-logo-horizontal.svg"));
    expect(svg).toContain(`stroke="${BRAND_COLORS.primary}"`);
    expect(svg).toContain(`fill="${BRAND_COLORS.ink}"`);
  });
});

describe("public icons", () => {
  it("ships an adaptive favicon.svg with the spec's construction", () => {
    const svg = read(path.join(ROOT, "public", "favicon.svg"));
    expect(svg).toContain("prefers-color-scheme: dark");
    expect(svg).toContain("<title>Tailrd</title>");
    for (const d of FAVICON.panels) expect(svg).toContain(`d="${d}"`);
  });

  it("points the manifest at the new icons", () => {
    const manifest = JSON.parse(read(path.join(ROOT, "public", "site.webmanifest")));
    expect(manifest.theme_color).toBe(BRAND_COLORS.primary);
    expect(manifest.icons.map((i: { src: string }) => i.src)).toEqual(["/icon-192.png", "/icon-512.png", "/icon-512-maskable.png"]);
    expect(manifest.icons[2].purpose).toBe("maskable");
  });
});
