/**
 * Profiles the e2e harness syncs into the real extension.
 *
 * MOCK mirrors src/api/mockProfile.ts (the extension's own sample data) so the
 * old in-page harness and this one agree on what "John Doe" answers. The others
 * are shaped like REAL profiles in production (2026-10-03 survey of stored
 * answers): sparse structured fields, free-text work authorization, a single
 * location string instead of a structured address.
 */
export const MOCK = {
  firstName: "John",
  lastName: "Doe",
  email: "john@example.com",
  phone: "+1 555 555 5555",
  location: "Ottawa, ON, Canada",
  addressStreet: "123 Example Street",
  addressCity: "",
  addressState: "ON",
  postalCode: "K1A 0A6",
  country: "Canada",
  linkedin: "https://linkedin.com/in/johndoe",
  github: "https://github.com/johndoe",
  portfolio: "https://johndoe.com",
  currentCompany: "Example Company",
  currentTitle: "Software Engineer",
  workAuthorization: "Authorized to work in Canada",
  requiresSponsorship: "No",
  dateOfBirth: "1999-03-14",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  noticePeriod: "2 weeks",
  earliestStartDate: "2026-09-01",
  yearsOfExperience: "3",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), French (Professional)",
  education: [{ school: "University of Ottawa", degree: "BSc Computer Science", graduationYear: "2026" }],
  experience: [
    {
      company: "Example Company",
      title: "Software Engineer Intern",
      startDate: "2025-05",
      endDate: "2025-08",
      description: "Built full-stack features using React, Node.js, and PostgreSQL.",
    },
  ],
  skills: ["JavaScript", "TypeScript", "React", "Node.js", "Python", "PostgreSQL"],
  coverLetter: "Please generate or insert the saved cover letter here.",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Heterosexual",
  },
};

/**
 * A sparse, realistic profile: what most real users actually have. No
 * structured address (only `location`), no stated years of experience, no
 * stated current title/company, work authorization as a free-text sentence.
 * Every answer the forms want beyond the basics has to be INFERRED.
 */
export const SPARSE_CANADIAN = {
  firstName: "Maya",
  lastName: "Tremblay",
  email: "maya.tremblay@example.com",
  phone: "(416) 555-0142",
  location: "Toronto, ON, Canada",
  addressStreet: "",
  addressCity: "",
  addressState: "",
  postalCode: "",
  country: "",
  linkedin: "https://www.linkedin.com/in/maya-tremblay",
  github: "",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "Canadian citizen",
  requiresSponsorship: "",
  dateOfBirth: "",
  education: [
    { school: "University of Waterloo", degree: "Bachelor of Applied Science in Mechatronics Engineering", graduationYear: "2027" },
  ],
  experience: [
    { company: "Shopify", title: "Software Developer Intern", startDate: "2025-01", endDate: "2025-04", description: "" },
    { company: "Kinaxis", title: "Software Engineer Co-op", startDate: "2025-09", endDate: "Present", description: "" },
  ],
  skills: ["Python", "C++", "ROS"],
  coverLetter: "",
};

/** A US-based applicant on a student visa: the sponsorship answer is YES. */
export const US_F1_STUDENT = {
  firstName: "Arjun",
  lastName: "Mehta",
  email: "arjun.mehta@example.com",
  phone: "+1 (617) 555-0199",
  location: "",
  addressStreet: "77 Massachusetts Ave, Apt 4B",
  addressCity: "Cambridge",
  addressState: "MA",
  postalCode: "02139",
  country: "United States",
  linkedin: "https://linkedin.com/in/arjunmehta",
  github: "https://github.com/arjunm",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "F-1 student visa (OPT eligible)",
  requiresSponsorship: "Yes",
  dateOfBirth: "2003-06-02",
  education: [{ school: "Massachusetts Institute of Technology", degree: "Master of Science in Computer Science", graduationYear: "2026" }],
  experience: [
    { company: "Acme Robotics", title: "Machine Learning Intern", startDate: "June 2024", endDate: "August 2024", description: "" },
  ],
  skills: ["Python", "PyTorch"],
  coverLetter: "",
};

/** Everything in ONE address string, nothing structured. */
export const ADDRESS_ONLY = {
  ...SPARSE_CANADIAN,
  firstName: "Sam",
  lastName: "Okafor",
  email: "sam.okafor@example.com",
  phone: "604-555-0177",
  location: "",
  addressStreet: "1055 W Georgia St, Vancouver, BC V6E 3P3, Canada",
  workAuthorization: "Permanent resident of Canada",
};

/**
 * A COMPLETE profile: SPARSE_CANADIAN after the user finished onboarding and
 * every Profile-page answer, the 2026-10-03 fields included (per-country work
 * authorization, channel, graduation month, GPA). The yardstick for "answers
 * every question without AI": what this profile leaves blank is either an
 * essay or a gap to close.
 */
export const COMPLETE_CANADIAN = {
  ...SPARSE_CANADIAN,
  country: "Canada",
  github: "https://github.com/mayatremblay",
  portfolio: "https://mayatremblay.dev",
  requiresSponsorship: "No",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "2004-02-11",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  noticePeriod: "2 weeks",
  earliestStartDate: "2027-05-03",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), French (Professional)",
  howDidYouHear: "LinkedIn",
  expectedGraduation: "2027-04",
  gpa: "3.7/4.0",
  salaryExpectation: "95000",
  eeo: {
    gender: "Female",
    genderIdentity: "Cisgender",
    pronouns: "She/Her",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Heterosexual",
  },
};

// ---------------------------------------------------------------------------
// Round 3 (2026-10-03): five personas that vary what the earlier five do not.
// Data shapes differ on purpose: phone, date, salary and URL formats, accents
// and apostrophes in names, several education rows, a current job ("Present"),
// a government employer, EEO answers across the vocabulary (including all
// declined), countries outside North America.

/** A US citizen and protected veteran (Army, then a degree), employed now, in
 *  Texas. Remote only, will not relocate, holds a clearance. */
export const US_VETERAN = {
  firstName: "Marcus",
  lastName: "Hill",
  email: "marcus.hill@example.com",
  phone: "512-555-0143",
  location: "Austin, TX",
  addressStreet: "4120 Duval St",
  addressCity: "Austin",
  addressState: "TX",
  postalCode: "78751",
  country: "United States",
  linkedin: "https://www.linkedin.com/in/marcus-hill-dev",
  github: "https://github.com/mhill-dev",
  portfolio: "",
  currentCompany: "Dell Technologies",
  currentTitle: "Software Engineer II",
  workAuthorization: "U.S. citizen",
  requiresSponsorship: "No",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "1994-03-12",
  willingToRelocate: "No",
  workPreference: "Remote",
  earliestStartDate: "2026-10-26",
  noticePeriod: "2 weeks",
  yearsOfExperience: "6",
  securityClearance: "Active clearance",
  driversLicense: "Yes",
  languages: "English (Native), Spanish (Conversational)",
  howDidYouHear: "Company website",
  gpa: "3.2",
  salaryExpectation: "$135,000",
  education: [{ school: "The University of Texas at Austin", degree: "Bachelor of Science in Computer Science", graduationYear: "2019" }],
  experience: [
    { company: "U.S. Army", title: "Signal Support Systems Specialist", startDate: "Jun 2012", endDate: "May 2016", description: "" },
    { company: "Indeed", title: "Software Engineer", startDate: "Jul 2019", endDate: "Dec 2022", description: "" },
    { company: "Dell Technologies", title: "Software Engineer II", startDate: "Jan 2023", endDate: "Present", description: "" },
  ],
  skills: ["Java", "Go", "AWS", "Kubernetes"],
  coverLetter: "",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "Black or African American",
    hispanicLatino: "No",
    veteranStatus: "I identify as one or more of the classifications of a protected veteran",
    disabilityStatus: "Prefer not to say",
    sexualOrientation: "Heterosexual",
  },
};

/** A senior engineer in London: no North American work right, needs
 *  sponsorship there, will relocate, three months' notice, pounds. */
export const UK_SENIOR = {
  firstName: "Siobhán",
  lastName: "O'Neill",
  email: "siobhan.oneill@example.co.uk",
  phone: "+44 20 7946 0958",
  location: "London, United Kingdom",
  addressStreet: "12 Bermondsey Street",
  addressCity: "London",
  addressState: "",
  postalCode: "SE1 3TQ",
  country: "United Kingdom",
  linkedin: "https://www.linkedin.com/in/siobhan-oneill",
  github: "https://github.com/soneill",
  portfolio: "https://soneill.dev",
  currentCompany: "Monzo",
  currentTitle: "Senior Backend Engineer",
  workAuthorization: "British citizen",
  requiresSponsorship: "Yes",
  authorizedUS: "No",
  authorizedCanada: "No",
  dateOfBirth: "",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  earliestStartDate: "2027-01-04",
  noticePeriod: "3 months",
  yearsOfExperience: "9",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), Irish (Fluent), French (Basic)",
  howDidYouHear: "LinkedIn",
  salaryExpectation: "£95,000",
  education: [
    { school: "Imperial College London", degree: "Master of Science in Computing", graduationYear: "2016" },
    { school: "Trinity College Dublin", degree: "Bachelor of Arts in Computer Science", graduationYear: "2015" },
  ],
  experience: [
    { company: "Deliveroo", title: "Software Engineer", startDate: "2016-09", endDate: "2021-03", description: "" },
    { company: "Monzo", title: "Senior Backend Engineer", startDate: "2021-04", endDate: "Present", description: "" },
  ],
  skills: ["Go", "Kafka", "PostgreSQL"],
  coverLetter: "",
  eeo: {
    gender: "Female",
    genderIdentity: "Transgender",
    pronouns: "She/Her",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "Yes, I have a disability",
    sexualOrientation: "Bisexual",
  },
};

/** A career changer in Montreal: permanent resident, French-first (accents,
 *  a French degree title, "75 000 $"), a former public-school teacher,
 *  non-binary, links without https. */
export const MONTREAL_CHANGER = {
  firstName: "Alex",
  lastName: "Côté-Tremblay",
  email: "alex.cote@example.ca",
  phone: "514 555 0186",
  location: "Montréal, QC",
  addressStreet: "4520 rue Saint-Denis, app. 3",
  addressCity: "Montréal",
  addressState: "QC",
  postalCode: "H2J 2L3",
  country: "Canada",
  linkedin: "linkedin.com/in/alexcote",
  github: "github.com/alexct",
  portfolio: "",
  currentCompany: "Lightspeed Commerce",
  currentTitle: "Junior Software Developer",
  workAuthorization: "Permanent resident of Canada",
  requiresSponsorship: "No",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "",
  willingToRelocate: "No",
  workPreference: "Remote",
  earliestStartDate: "2026-11-16",
  securityClearance: "None",
  driversLicense: "No",
  languages: "French (Native), English (Fluent)",
  howDidYouHear: "Referral",
  salaryExpectation: "75 000 $",
  education: [
    { school: "Université de Montréal", degree: "Baccalauréat en psychologie", graduationYear: "2017" },
    { school: "Concordia University", degree: "Certificate in Computer Science", graduationYear: "2023" },
  ],
  experience: [
    { company: "Commission scolaire de Montréal", title: "Teacher", startDate: "2017-08", endDate: "2023-06", description: "" },
    { company: "Lightspeed Commerce", title: "Junior Software Developer", startDate: "2024-02", endDate: "Present", description: "" },
  ],
  skills: ["TypeScript", "React", "Node.js"],
  coverLetter: "",
  eeo: {
    gender: "Non-binary",
    genderIdentity: "Non-binary",
    pronouns: "They/Them",
    race: "Two or More Races",
    hispanicLatino: "Yes",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Gay or Lesbian",
  },
};

/** A new graduate in Calgary: no work experience, no links, every EEO
 *  question declined, on-site, starts next week. */
export const NEW_GRAD_DECLINER = {
  firstName: "Priya",
  lastName: "Nair",
  email: "priya.nair@example.com",
  phone: "(403) 555-0123",
  location: "Calgary, AB, Canada",
  addressStreet: "",
  addressCity: "",
  addressState: "",
  postalCode: "",
  country: "Canada",
  linkedin: "",
  github: "",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "Canadian citizen",
  requiresSponsorship: "",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "",
  willingToRelocate: "Yes",
  workPreference: "On-site",
  earliestStartDate: "2026-10-06",
  driversLicense: "No",
  howDidYouHear: "Job board",
  gpa: "3.9/4.0",
  education: [{ school: "University of Calgary", degree: "Bachelor of Science in Electrical Engineering", graduationYear: "2026-05" }],
  experience: [],
  skills: ["MATLAB", "Python", "C"],
  coverLetter: "",
  eeo: {
    gender: "Prefer not to say",
    genderIdentity: "Prefer not to say",
    pronouns: "Prefer not to say",
    race: "Prefer not to say",
    hispanicLatino: "Prefer not to say",
    veteranStatus: "Prefer not to say",
    disabilityStatus: "Prefer not to say",
    sexualOrientation: "Prefer not to say",
  },
};

/** A US permanent resident (a "US person" for export control) studying in
 *  California: a TA job running now at a public university, an hourly rate,
 *  "USA" and a spelled-out state. */
export const US_GREENCARD_STUDENT = {
  firstName: "Mei",
  lastName: "Lin",
  email: "mei.lin@example.edu",
  phone: "+1 408-555-0172",
  location: "San Jose, CA",
  addressStreet: "1 Washington Sq",
  addressCity: "San Jose",
  addressState: "California",
  postalCode: "95192",
  country: "USA",
  linkedin: "https://www.linkedin.com/in/meilin",
  github: "https://github.com/meilin",
  portfolio: "https://meilin.github.io",
  currentCompany: "San José State University",
  currentTitle: "Teaching Assistant",
  workAuthorization: "U.S. permanent resident (green card)",
  requiresSponsorship: "No",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "2004-11-20",
  willingToRelocate: "Yes",
  workPreference: "On-site",
  earliestStartDate: "2027-05-24",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Fluent), Mandarin (Native)",
  howDidYouHear: "Career fair",
  expectedGraduation: "2027-12",
  gpa: "3.6",
  salaryExpectation: "$45/hour",
  education: [{ school: "San José State University", degree: "Bachelor of Science in Software Engineering", graduationYear: "2027" }],
  experience: [
    { company: "San José State University", title: "Teaching Assistant", startDate: "Aug 2025", endDate: "Present", description: "" },
    { company: "Cisco", title: "Software Engineering Intern", startDate: "May 2025", endDate: "Aug 2025", description: "" },
  ],
  skills: ["Python", "Java", "SQL"],
  coverLetter: "",
  eeo: {
    gender: "Female",
    genderIdentity: "Cisgender",
    pronouns: "She/Her",
    race: "Asian",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Prefer not to say",
  },
};

// ---------------------------------------------------------------------------
// Round 4 (2026-10-05): five personas that vary what rounds 1 to 3 did not.
// A US worker on H-1B and one on STEM OPT (authorized now, sponsorship
// needed), no degree (a bootcamp and high school), seven jobs listed newest
// first, a career gap and a disability answered "Yes", names with tone marks,
// an apostrophe and a hyphen, and addresses in Germany and India.

/** A senior data engineer in Seattle on H-1B: authorized now, needs
 *  sponsorship (a transfer). Seven jobs, NEWEST FIRST as a resume lists them,
 *  a master's in the US and a bachelor's in Vietnam. Vietnamese name with
 *  tone marks, family name last on forms. */
export const US_H1B_SENIOR = {
  firstName: "Thu Hà",
  lastName: "Nguyễn",
  email: "thuha.nguyen@example.com",
  phone: "(206) 555-0131",
  location: "Seattle, WA",
  addressStreet: "1200 Westlake Ave N, Unit 805",
  addressCity: "Seattle",
  addressState: "WA",
  postalCode: "98109",
  country: "United States",
  linkedin: "https://www.linkedin.com/in/thuha-nguyen",
  github: "https://github.com/thuhanguyen",
  portfolio: "",
  currentCompany: "Expedia Group",
  currentTitle: "Senior Data Engineer",
  workAuthorization: "H-1B visa (transfer required)",
  requiresSponsorship: "Yes",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "1988-09-05",
  willingToRelocate: "No",
  workPreference: "Hybrid",
  earliestStartDate: "2026-11-30",
  noticePeriod: "4 weeks",
  yearsOfExperience: "15",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "Vietnamese (Native), English (Fluent)",
  howDidYouHear: "Company website",
  salaryExpectation: "$185,000",
  education: [
    { school: "University of Washington", degree: "Master of Science in Information Systems", graduationYear: "2014" },
    { school: "Hanoi University of Science and Technology", degree: "Bachelor of Engineering in Computer Science", graduationYear: "2011" },
  ],
  experience: [
    { company: "Expedia Group", title: "Senior Data Engineer", startDate: "2023-11", endDate: "Present", description: "" },
    { company: "Redfin", title: "Senior Data Engineer", startDate: "2021-09", endDate: "2023-10", description: "" },
    { company: "Amazon", title: "Data Engineer", startDate: "2019-06", endDate: "2021-08", description: "" },
    { company: "Tableau Software", title: "Data Engineer II", startDate: "2017-01", endDate: "2019-05", description: "" },
    { company: "Zillow", title: "Data Engineer", startDate: "2014-07", endDate: "2016-12", description: "" },
    { company: "University of Washington", title: "Research Assistant", startDate: "2012-09", endDate: "2014-06", description: "" },
    { company: "FPT Software", title: "Software Engineer", startDate: "2011-07", endDate: "2012-08", description: "" },
  ],
  skills: ["Python", "Spark", "Airflow", "SQL"],
  coverLetter: "",
  eeo: {
    gender: "Female",
    genderIdentity: "Cisgender",
    pronouns: "She/Her",
    race: "Asian",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Heterosexual",
  },
};

/** A US citizen in Denver with no degree: high school, then a coding
 *  bootcamp. A five-year career change with a three-year gap (caregiving),
 *  out of work since June, a disability answered "Yes". Apostrophe and hyphen
 *  in the name, a dotted phone, the state spelled out, "US" as the country. */
export const BOOTCAMP_CAREER_GAP = {
  firstName: "D'Andre",
  lastName: "Jean-Baptiste",
  email: "dandre.jb@example.com",
  phone: "720.555.0164",
  location: "Denver, CO",
  addressStreet: "2750 Welton St",
  addressCity: "Denver",
  addressState: "Colorado",
  postalCode: "80205",
  country: "US",
  linkedin: "https://linkedin.com/in/dandre-jean-baptiste/",
  github: "https://github.com/djeanbaptiste",
  portfolio: "https://dandre.codes",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "US Citizen",
  requiresSponsorship: "No",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "1991-01-30",
  willingToRelocate: "No",
  workPreference: "Remote",
  earliestStartDate: "2026-10-19",
  noticePeriod: "Immediately",
  yearsOfExperience: "3",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), Haitian Creole (Conversational)",
  howDidYouHear: "Social media",
  salaryExpectation: "85000",
  education: [
    { school: "Turing School of Software & Design", degree: "Certificate in Back-End Engineering", graduationYear: "2022" },
    { school: "East High School", degree: "High School Diploma", graduationYear: "2009" },
  ],
  experience: [
    { company: "Home Depot", title: "Sales Associate", startDate: "2010-03", endDate: "2014-08", description: "" },
    { company: "Enterprise Rent-A-Car", title: "Branch Assistant Manager", startDate: "2014-09", endDate: "2019-05", description: "" },
    { company: "Ibotta", title: "Junior Software Engineer", startDate: "2022-08", endDate: "2026-06", description: "" },
  ],
  skills: ["Ruby", "Rails", "JavaScript", "PostgreSQL"],
  coverLetter: "",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "Black or African American",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "Yes, I have a disability",
    sexualOrientation: "Prefer not to say",
  },
};

/** A data analyst in Boston on F-1 STEM OPT: authorized now through an EAD,
 *  needs sponsorship later. A US master's, a Korean bachelor's, a hyphenated
 *  given name, "United States of America", salary written "95,000 USD". */
export const US_OPT_ANALYST = {
  firstName: "Ji-woo",
  lastName: "Park",
  email: "jiwoo.park@example.com",
  phone: "+1 617 555 0148",
  location: "Boston, MA, USA",
  addressStreet: "88 Brookline Ave, Apt 12C",
  addressCity: "Boston",
  addressState: "MA",
  postalCode: "02215",
  country: "United States of America",
  linkedin: "https://www.linkedin.com/in/jiwoo-park-data",
  github: "",
  portfolio: "https://jiwoopark.io",
  currentCompany: "Wayfair",
  currentTitle: "Data Analyst",
  workAuthorization: "F-1 STEM OPT (EAD valid through June 2028)",
  requiresSponsorship: "Yes",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "1999-04-17",
  willingToRelocate: "Yes",
  workPreference: "On-site",
  earliestStartDate: "2026-11-02",
  noticePeriod: "2 weeks",
  yearsOfExperience: "1",
  securityClearance: "None",
  driversLicense: "No",
  languages: "Korean (Native), English (Fluent)",
  howDidYouHear: "Job board",
  gpa: "3.85",
  salaryExpectation: "95,000 USD",
  education: [
    { school: "Northeastern University", degree: "Master of Science in Data Science", graduationYear: "2025-05" },
    { school: "Yonsei University", degree: "Bachelor of Business Administration", graduationYear: "2022" },
  ],
  experience: [
    { company: "Wayfair", title: "Data Analyst", startDate: "2025-07", endDate: "Present", description: "" },
    { company: "Samsung SDS", title: "Business Analyst Intern", startDate: "2021-06", endDate: "2021-08", description: "" },
  ],
  skills: ["SQL", "Python", "Tableau"],
  coverLetter: "",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "Asian",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Gay or Lesbian",
  },
};

/** A staff engineer in Berlin: German citizen, no North American work right,
 *  needs sponsorship there, will relocate. Umlaut and eszett in the name and
 *  street, a German postal code, a Diplom (neither a bachelor's nor a
 *  master's by name), euros with a dot for thousands. */
export const BERLIN_STAFF = {
  firstName: "Jürgen",
  lastName: "Weiß",
  email: "juergen.weiss@example.de",
  phone: "+49 30 12345678",
  location: "Berlin, Germany",
  addressStreet: "Torstraße 109",
  addressCity: "Berlin",
  addressState: "Berlin",
  postalCode: "10119",
  country: "Germany",
  linkedin: "https://www.linkedin.com/in/juergen-weiss",
  github: "https://github.com/jweiss",
  portfolio: "",
  currentCompany: "Zalando SE",
  currentTitle: "Staff Engineer",
  workAuthorization: "German citizen (EU)",
  requiresSponsorship: "Yes",
  authorizedUS: "No",
  authorizedCanada: "No",
  dateOfBirth: "1984-06-21",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  earliestStartDate: "2027-02-01",
  noticePeriod: "3 months",
  yearsOfExperience: "14",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "German (Native), English (Fluent)",
  howDidYouHear: "Referral",
  salaryExpectation: "€120.000",
  education: [{ school: "Technische Universität München", degree: "Diplom-Informatiker", graduationYear: "2011" }],
  experience: [
    { company: "SAP", title: "Software Developer", startDate: "2011-10", endDate: "2016-03", description: "" },
    { company: "SoundCloud", title: "Senior Engineer", startDate: "2016-04", endDate: "2020-12", description: "" },
    { company: "Zalando SE", title: "Staff Engineer", startDate: "2021-01", endDate: "Present", description: "" },
  ],
  skills: ["Kotlin", "Scala", "Kafka"],
  coverLetter: "",
  eeo: {
    gender: "Male",
    genderIdentity: "Transgender",
    pronouns: "He/Him",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "Prefer not to say",
    sexualOrientation: "Bisexual",
  },
};

/** A new graduate in Bengaluru: Indian citizen, needs sponsorship anywhere
 *  else, a CGPA out of 10 (not 4.0), a six-digit PIN code, the state spelled
 *  out, phone with +91. Will relocate; no EEO answers stated. */
export const INDIA_NEW_GRAD = {
  firstName: "Ananya",
  lastName: "Raghavan",
  email: "ananya.raghavan@example.in",
  phone: "+91 98450 12345",
  location: "Bengaluru, Karnataka, India",
  addressStreet: "14, 5th Cross, Indiranagar",
  addressCity: "Bengaluru",
  addressState: "Karnataka",
  postalCode: "560038",
  country: "India",
  linkedin: "https://www.linkedin.com/in/ananya-raghavan",
  github: "https://github.com/ananyar",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "Indian citizen",
  requiresSponsorship: "Yes",
  authorizedUS: "No",
  authorizedCanada: "No",
  dateOfBirth: "2003-08-09",
  willingToRelocate: "Yes",
  workPreference: "No preference",
  earliestStartDate: "2026-12-01",
  noticePeriod: "Immediately",
  securityClearance: "None",
  driversLicense: "No",
  languages: "English (Fluent), Tamil (Native), Kannada (Conversational), Hindi (Conversational)",
  howDidYouHear: "LinkedIn",
  expectedGraduation: "2026-06",
  gpa: "8.6/10",
  education: [{ school: "Indian Institute of Technology Madras", degree: "Bachelor of Technology in Computer Science and Engineering", graduationYear: "2026" }],
  experience: [
    { company: "Flipkart", title: "Software Engineering Intern", startDate: "2025-05", endDate: "2025-07", description: "" },
  ],
  skills: ["Java", "Python", "Distributed Systems"],
  coverLetter: "",
};
