/**
 * Profiles the e2e harness syncs into the real extension.
 *
 * MOCK mirrors src/api/mockProfile.ts (the extension's own sample data) so the
 * old in-page harness and this one agree on what "John Doe" answers. The others
 * are shaped like REAL profiles in production (2026-10-03 survey of stored
 * answers): sparse structured fields, free-text work authorization, a single
 * location string instead of a structured address.
 */
export const MOCK = {
  firstName: "John",
  lastName: "Doe",
  email: "john@example.com",
  phone: "+1 555 555 5555",
  location: "Ottawa, ON, Canada",
  addressStreet: "123 Example Street",
  addressCity: "",
  addressState: "ON",
  postalCode: "K1A 0A6",
  country: "Canada",
  linkedin: "https://linkedin.com/in/johndoe",
  github: "https://github.com/johndoe",
  portfolio: "https://johndoe.com",
  currentCompany: "Example Company",
  currentTitle: "Software Engineer",
  workAuthorization: "Authorized to work in Canada",
  requiresSponsorship: "No",
  dateOfBirth: "1999-03-14",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  noticePeriod: "2 weeks",
  earliestStartDate: "2026-09-01",
  yearsOfExperience: "3",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), French (Professional)",
  education: [{ school: "University of Ottawa", degree: "BSc Computer Science", graduationYear: "2026" }],
  experience: [
    {
      company: "Example Company",
      title: "Software Engineer Intern",
      startDate: "2025-05",
      endDate: "2025-08",
      description: "Built full-stack features using React, Node.js, and PostgreSQL.",
    },
  ],
  skills: ["JavaScript", "TypeScript", "React", "Node.js", "Python", "PostgreSQL"],
  coverLetter: "Please generate or insert the saved cover letter here.",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Heterosexual",
  },
};

/**
 * A sparse, realistic profile: what most real users actually have. No
 * structured address (only `location`), no stated years of experience, no
 * stated current title/company, work authorization as a free-text sentence.
 * Every answer the forms want beyond the basics has to be INFERRED.
 */
export const SPARSE_CANADIAN = {
  firstName: "Maya",
  lastName: "Tremblay",
  email: "maya.tremblay@example.com",
  phone: "(416) 555-0142",
  location: "Toronto, ON, Canada",
  addressStreet: "",
  addressCity: "",
  addressState: "",
  postalCode: "",
  country: "",
  linkedin: "https://www.linkedin.com/in/maya-tremblay",
  github: "",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "Canadian citizen",
  requiresSponsorship: "",
  dateOfBirth: "",
  education: [
    { school: "University of Waterloo", degree: "Bachelor of Applied Science in Mechatronics Engineering", graduationYear: "2027" },
  ],
  experience: [
    { company: "Shopify", title: "Software Developer Intern", startDate: "2025-01", endDate: "2025-04", description: "" },
    { company: "Kinaxis", title: "Software Engineer Co-op", startDate: "2025-09", endDate: "Present", description: "" },
  ],
  skills: ["Python", "C++", "ROS"],
  coverLetter: "",
};

/** A US-based applicant on a student visa: the sponsorship answer is YES. */
export const US_F1_STUDENT = {
  firstName: "Arjun",
  lastName: "Mehta",
  email: "arjun.mehta@example.com",
  phone: "+1 (617) 555-0199",
  location: "",
  addressStreet: "77 Massachusetts Ave, Apt 4B",
  addressCity: "Cambridge",
  addressState: "MA",
  postalCode: "02139",
  country: "United States",
  linkedin: "https://linkedin.com/in/arjunmehta",
  github: "https://github.com/arjunm",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "F-1 student visa (OPT eligible)",
  requiresSponsorship: "Yes",
  dateOfBirth: "2003-06-02",
  education: [{ school: "Massachusetts Institute of Technology", degree: "Master of Science in Computer Science", graduationYear: "2026" }],
  experience: [
    { company: "Acme Robotics", title: "Machine Learning Intern", startDate: "June 2024", endDate: "August 2024", description: "" },
  ],
  skills: ["Python", "PyTorch"],
  coverLetter: "",
};

/** Everything in ONE address string, nothing structured. */
export const ADDRESS_ONLY = {
  ...SPARSE_CANADIAN,
  firstName: "Sam",
  lastName: "Okafor",
  email: "sam.okafor@example.com",
  phone: "604-555-0177",
  location: "",
  addressStreet: "1055 W Georgia St, Vancouver, BC V6E 3P3, Canada",
  workAuthorization: "Permanent resident of Canada",
};

/**
 * A COMPLETE profile: SPARSE_CANADIAN after the user finished onboarding and
 * every Profile-page answer, the 2026-10-03 fields included (per-country work
 * authorization, channel, graduation month, GPA). The yardstick for "answers
 * every question without AI": what this profile leaves blank is either an
 * essay or a gap to close.
 */
export const COMPLETE_CANADIAN = {
  ...SPARSE_CANADIAN,
  country: "Canada",
  github: "https://github.com/mayatremblay",
  portfolio: "https://mayatremblay.dev",
  requiresSponsorship: "No",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "2004-02-11",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  noticePeriod: "2 weeks",
  earliestStartDate: "2027-05-03",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), French (Professional)",
  howDidYouHear: "LinkedIn",
  expectedGraduation: "2027-04",
  gpa: "3.7/4.0",
  salaryExpectation: "95000",
  eeo: {
    gender: "Female",
    genderIdentity: "Cisgender",
    pronouns: "She/Her",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Heterosexual",
  },
};

// ---------------------------------------------------------------------------
// Round 3 (2026-10-03): five personas that vary what the earlier five do not.
// Data shapes differ on purpose: phone, date, salary and URL formats, accents
// and apostrophes in names, several education rows, a current job ("Present"),
// a government employer, EEO answers across the vocabulary (including all
// declined), countries outside North America.

/** A US citizen and protected veteran (Army, then a degree), employed now, in
 *  Texas. Remote only, will not relocate, holds a clearance. */
export const US_VETERAN = {
  firstName: "Marcus",
  lastName: "Hill",
  email: "marcus.hill@example.com",
  phone: "512-555-0143",
  location: "Austin, TX",
  addressStreet: "4120 Duval St",
  addressCity: "Austin",
  addressState: "TX",
  postalCode: "78751",
  country: "United States",
  linkedin: "https://www.linkedin.com/in/marcus-hill-dev",
  github: "https://github.com/mhill-dev",
  portfolio: "",
  currentCompany: "Dell Technologies",
  currentTitle: "Software Engineer II",
  workAuthorization: "U.S. citizen",
  requiresSponsorship: "No",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "1994-03-12",
  willingToRelocate: "No",
  workPreference: "Remote",
  earliestStartDate: "2026-10-26",
  noticePeriod: "2 weeks",
  yearsOfExperience: "6",
  securityClearance: "Active clearance",
  driversLicense: "Yes",
  languages: "English (Native), Spanish (Conversational)",
  howDidYouHear: "Company website",
  gpa: "3.2",
  salaryExpectation: "$135,000",
  education: [{ school: "The University of Texas at Austin", degree: "Bachelor of Science in Computer Science", graduationYear: "2019" }],
  experience: [
    { company: "U.S. Army", title: "Signal Support Systems Specialist", startDate: "Jun 2012", endDate: "May 2016", description: "" },
    { company: "Indeed", title: "Software Engineer", startDate: "Jul 2019", endDate: "Dec 2022", description: "" },
    { company: "Dell Technologies", title: "Software Engineer II", startDate: "Jan 2023", endDate: "Present", description: "" },
  ],
  skills: ["Java", "Go", "AWS", "Kubernetes"],
  coverLetter: "",
  eeo: {
    gender: "Male",
    genderIdentity: "Cisgender",
    pronouns: "He/Him",
    race: "Black or African American",
    hispanicLatino: "No",
    veteranStatus: "I identify as one or more of the classifications of a protected veteran",
    disabilityStatus: "Prefer not to say",
    sexualOrientation: "Heterosexual",
  },
};

/** A senior engineer in London: no North American work right, needs
 *  sponsorship there, will relocate, three months' notice, pounds. */
export const UK_SENIOR = {
  firstName: "Siobhán",
  lastName: "O'Neill",
  email: "siobhan.oneill@example.co.uk",
  phone: "+44 20 7946 0958",
  location: "London, United Kingdom",
  addressStreet: "12 Bermondsey Street",
  addressCity: "London",
  addressState: "",
  postalCode: "SE1 3TQ",
  country: "United Kingdom",
  linkedin: "https://www.linkedin.com/in/siobhan-oneill",
  github: "https://github.com/soneill",
  portfolio: "https://soneill.dev",
  currentCompany: "Monzo",
  currentTitle: "Senior Backend Engineer",
  workAuthorization: "British citizen",
  requiresSponsorship: "Yes",
  authorizedUS: "No",
  authorizedCanada: "No",
  dateOfBirth: "",
  willingToRelocate: "Yes",
  workPreference: "Hybrid",
  earliestStartDate: "2027-01-04",
  noticePeriod: "3 months",
  yearsOfExperience: "9",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Native), Irish (Fluent), French (Basic)",
  howDidYouHear: "LinkedIn",
  salaryExpectation: "£95,000",
  education: [
    { school: "Imperial College London", degree: "Master of Science in Computing", graduationYear: "2016" },
    { school: "Trinity College Dublin", degree: "Bachelor of Arts in Computer Science", graduationYear: "2015" },
  ],
  experience: [
    { company: "Deliveroo", title: "Software Engineer", startDate: "2016-09", endDate: "2021-03", description: "" },
    { company: "Monzo", title: "Senior Backend Engineer", startDate: "2021-04", endDate: "Present", description: "" },
  ],
  skills: ["Go", "Kafka", "PostgreSQL"],
  coverLetter: "",
  eeo: {
    gender: "Female",
    genderIdentity: "Transgender",
    pronouns: "She/Her",
    race: "White",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "Yes, I have a disability",
    sexualOrientation: "Bisexual",
  },
};

/** A career changer in Montreal: permanent resident, French-first (accents,
 *  a French degree title, "75 000 $"), a former public-school teacher,
 *  non-binary, links without https. */
export const MONTREAL_CHANGER = {
  firstName: "Alex",
  lastName: "Côté-Tremblay",
  email: "alex.cote@example.ca",
  phone: "514 555 0186",
  location: "Montréal, QC",
  addressStreet: "4520 rue Saint-Denis, app. 3",
  addressCity: "Montréal",
  addressState: "QC",
  postalCode: "H2J 2L3",
  country: "Canada",
  linkedin: "linkedin.com/in/alexcote",
  github: "github.com/alexct",
  portfolio: "",
  currentCompany: "Lightspeed Commerce",
  currentTitle: "Junior Software Developer",
  workAuthorization: "Permanent resident of Canada",
  requiresSponsorship: "No",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "",
  willingToRelocate: "No",
  workPreference: "Remote",
  earliestStartDate: "2026-11-16",
  securityClearance: "None",
  driversLicense: "No",
  languages: "French (Native), English (Fluent)",
  howDidYouHear: "Referral",
  salaryExpectation: "75 000 $",
  education: [
    { school: "Université de Montréal", degree: "Baccalauréat en psychologie", graduationYear: "2017" },
    { school: "Concordia University", degree: "Certificate in Computer Science", graduationYear: "2023" },
  ],
  experience: [
    { company: "Commission scolaire de Montréal", title: "Teacher", startDate: "2017-08", endDate: "2023-06", description: "" },
    { company: "Lightspeed Commerce", title: "Junior Software Developer", startDate: "2024-02", endDate: "Present", description: "" },
  ],
  skills: ["TypeScript", "React", "Node.js"],
  coverLetter: "",
  eeo: {
    gender: "Non-binary",
    genderIdentity: "Non-binary",
    pronouns: "They/Them",
    race: "Two or More Races",
    hispanicLatino: "Yes",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Gay or Lesbian",
  },
};

/** A new graduate in Calgary: no work experience, no links, every EEO
 *  question declined, on-site, starts next week. */
export const NEW_GRAD_DECLINER = {
  firstName: "Priya",
  lastName: "Nair",
  email: "priya.nair@example.com",
  phone: "(403) 555-0123",
  location: "Calgary, AB, Canada",
  addressStreet: "",
  addressCity: "",
  addressState: "",
  postalCode: "",
  country: "Canada",
  linkedin: "",
  github: "",
  portfolio: "",
  currentCompany: "",
  currentTitle: "",
  workAuthorization: "Canadian citizen",
  requiresSponsorship: "",
  authorizedUS: "No",
  authorizedCanada: "Yes",
  dateOfBirth: "",
  willingToRelocate: "Yes",
  workPreference: "On-site",
  earliestStartDate: "2026-10-06",
  driversLicense: "No",
  howDidYouHear: "Job board",
  gpa: "3.9/4.0",
  education: [{ school: "University of Calgary", degree: "Bachelor of Science in Electrical Engineering", graduationYear: "2026-05" }],
  experience: [],
  skills: ["MATLAB", "Python", "C"],
  coverLetter: "",
  eeo: {
    gender: "Prefer not to say",
    genderIdentity: "Prefer not to say",
    pronouns: "Prefer not to say",
    race: "Prefer not to say",
    hispanicLatino: "Prefer not to say",
    veteranStatus: "Prefer not to say",
    disabilityStatus: "Prefer not to say",
    sexualOrientation: "Prefer not to say",
  },
};

/** A US permanent resident (a "US person" for export control) studying in
 *  California: a TA job running now at a public university, an hourly rate,
 *  "USA" and a spelled-out state. */
export const US_GREENCARD_STUDENT = {
  firstName: "Mei",
  lastName: "Lin",
  email: "mei.lin@example.edu",
  phone: "+1 408-555-0172",
  location: "San Jose, CA",
  addressStreet: "1 Washington Sq",
  addressCity: "San Jose",
  addressState: "California",
  postalCode: "95192",
  country: "USA",
  linkedin: "https://www.linkedin.com/in/meilin",
  github: "https://github.com/meilin",
  portfolio: "https://meilin.github.io",
  currentCompany: "San José State University",
  currentTitle: "Teaching Assistant",
  workAuthorization: "U.S. permanent resident (green card)",
  requiresSponsorship: "No",
  authorizedUS: "Yes",
  authorizedCanada: "No",
  dateOfBirth: "2004-11-20",
  willingToRelocate: "Yes",
  workPreference: "On-site",
  earliestStartDate: "2027-05-24",
  securityClearance: "None",
  driversLicense: "Yes",
  languages: "English (Fluent), Mandarin (Native)",
  howDidYouHear: "Career fair",
  expectedGraduation: "2027-12",
  gpa: "3.6",
  salaryExpectation: "$45/hour",
  education: [{ school: "San José State University", degree: "Bachelor of Science in Software Engineering", graduationYear: "2027" }],
  experience: [
    { company: "San José State University", title: "Teaching Assistant", startDate: "Aug 2025", endDate: "Present", description: "" },
    { company: "Cisco", title: "Software Engineering Intern", startDate: "May 2025", endDate: "Aug 2025", description: "" },
  ],
  skills: ["Python", "Java", "SQL"],
  coverLetter: "",
  eeo: {
    gender: "Female",
    genderIdentity: "Cisgender",
    pronouns: "She/Her",
    race: "Asian",
    hispanicLatino: "No",
    veteranStatus: "I have never served in the military",
    disabilityStatus: "No, I do not have a disability",
    sexualOrientation: "Prefer not to say",
  },
};
